FROM ubuntu:latest

RUN set -xe \
    && apt-get update -y \
    && apt-get install python3-pip -y
RUN pip install --upgrade pip


COPY install/requirements.server.prod.txt /tmp/
RUN pip install -r /tmp/requirements.server.prod.txt


COPY server/app.py /app.py
EXPOSE 5000
ENTRYPOINT [ "python3" ]
CMD [ "app.py", "--dev", "False" ]

