FROM ubuntu:latest

RUN set -xe \
    && apt-get update -y \
    && apt-get install python3-pip -y
RUN pip install --upgrade pip

COPY requirements.prod.txt /tmp/
RUN pip install -r /tmp/requirements.prod.txt

COPY app.py /app.py
EXPOSE 8050
ENTRYPOINT [ "python3" ]
CMD [ "app.py", "--dev", "False" ]
