apiVersion: apps/v1
kind: ReplicaSet
metadata:
  creationTimestamp: "2023-01-19T10:12:06Z"
  generation: 2
  name: new-replica-set
  namespace: default
  resourceVersion: "1368"
  uid: 0c84fc3b-6653-4fdc-bcc3-4135aeb8f59c
spec:
  replicas: 4
  selector:
    matchLabels:
      name: busybox-pod
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: busybox-pod
    spec:
      containers:
      - command:
        - sh
        - -c
        - echo Hello Kubernetes! && sleep 3600
        image: busybox
        imagePullPolicy: Always
        name: busybox-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  fullyLabeledReplicas: 4
  observedGeneration: 2
  readyReplicas: 4
  replicas: 4