name: .NET Win2019 

on:
  push:
    branches: [ win2019 ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Sample Test
      run: |
        cd cs/sample
        dotnet restore
        dotnet build --no-restore
        dotnet test --no-build --verbosity normal
