name: Python CI MacOS Monterey

on:
  push:
    branches: [ macOS_Monterey ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-11

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8

      # Test python scripts
      - name: Test with pytest
        run: |
          cd py
          brew install sqlite3 
          pip install pytest parameterized numpy pandas multiset==2.1.1
          pytest
